### ISSUE TITLE
Errors on running Grunt server

### ISSUE THREAD

**Issue by nicxvan** [north/generator-style-prototype#11]
I followed the instructions installing dependencies listed on the home page of the project. The only other packages installed on the machine are Apache Mysql and PHP.

Ubuntu 12.04 Desktop.

Running yo style-prototype works as expected.
After entering the directory and running grunt server I get the error:

> > /bin/sh: 1:
> > weinre: not found
> > Exited with code: 127.
> > Warning: Task "exec:weinre" failed. Use --force to continue.
> > Running "watch" task

Aborted due to warnings.
    >> 
    Waiting...Warning: Task "parallel:remote" failed. Use --force to continue.

Aborted due to warnings.
###### Running it again gives this error

Waiting...>> /bin/sh: 1:

> > weinre: not found
> > Exited with code: 127.
> > Warning: Task "exec:weinre" failed. Use --force to continue.

Aborted due to warnings.
Fatal error: Port 8001 is already in use by another process.
    >> 
    >> 
Warning: Task "parallel:remote" failed. Use --force to continue.

Aborted due to warnings.
Waiting...>> /bin/sh: 1:

> > weinre: not found
> > Exited with code: 127.
> > Warning: Task "exec:weinre" failed. Use --force to continue.

Aborted due to warnings.
Fatal error: Port 8001 is already in use by another process.
    >> 
    >> 
Warning: Task "parallel:remote" failed. Use --force to continue.
###### ##################Visiting nicxvan.local:8001 shows

{"tinylr": "Welcome","version":"0.0.4"

**Comment by nicxvan** [comment]
I saw somewhere in this that weinre was not found so I tried npm install -g weinre to no success and many errors.

**Comment by nicxvan** [comment]
Ok so sudo npm install -g weinre installed weinre correctly and now grunt server works as expected.

I am leaving this open because I assume that weinre should install correctly by itself.

**Comment by nicxvan** [comment]
At the risk of showing my lack of knowledge: The only other things I noticed to make it work are the following. I only mention it to track my process, but I suspect these are due to my still relative newness to the desktop version of Ubuntu and Ruby.

I need to /bin/bash --login upon starting the terminal or my shell doesn't react quite right.
I need to rvm use ruby before running commands.

**Comment by nicxvan** [comment]
I was able to get it working, my process is as follows:

1 Fresh install of ubuntu
2 Open terminal and ensure it's using bash (/bin/bash --login)
3 Install project dependencies: nodel.js Ruby Git and Ruby Gems
4 Install the project using the instructions
5 Manually install weinre using sudo
6 Create project (occasionally it hangs, if it doesn't then continue)
7 Follow Issue #6 
7a delete "prism": "latest", from bower.json
7b  Run bower install again which downloads all components except prism
7c Install prism manually but this time specifying the target as 'bower install prism#gh-pages'
8 grunt server

If you try running grunt server before doing the above you will get errors about ports already being in use.

**Comment by Snugug** [comment]
Solved with #16 and cf4019e897fa4552b0ad3adc3d70ba7c143ea86f plus changing the port in `config.yml`
