### ISSUE TITLE
Bower hangs when creating a new Style Prototype

### ISSUE THREAD

**Issue by nicxvan** [north/generator-style-prototype#12]
Same set up as in #11:
Running yo style-prototype occasionally results in a success message followed by many bower lines.

The cli stops indefinitely (currently at 3 hours) at:
bower jquery#~2.0.0   validate 2.0.3 against git://github.com/components/jquery.git#~2.0.0

aborting seems to result in an incomplete style-prototype running grunt server at that point results in the following errors:
Fetching source index from https://rubygems.org/
Could not fetch specs from https://rubygems.org/

> > Exited with code: 17.
> > Warning: Task "exec:bundle:." failed. Use --force to continue.

Aborted due to warnings.
nicxvan@Nicxvan:~/Public/testing2$ grunt server
Loading "watch.js" tasks...ERROR

> > Error: Cannot find module 'inherits'
> > Loading "uglify.js" tasks...ERROR
> > Error: Cannot find module 'amdefine'

Running "server" task

Running "bundler" task

Running "exec:bundle:." (exec) task
Fetching source index from https://rubygems.org/
Could not fetch specs from https://rubygems.org/

> > Exited with code: 17.
> > Warning: Task "exec:bundle:." failed. Use --force to continue.

**Comment by nicxvan** [comment]
Following the same steps above but running rvm use ruby first results in the following errors on runnig grunt server

module.js:340
    throw err;
          ^
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/nicxvan/Public/testing3/node_modules/grunt/lib/grunt.js:16:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I'm getting good at making errors if anything. If anything. I am going to test another generator to try to rule out failure points.

**Comment by Snugug** [comment]
I believe this may have something to do with how we were previously pulling in Prism, which has since been solved. I am unable to recreate any hang with the current version on any platform (OS X, Ubuntu, Windows), nonetheless a 3 hour hang.

**Comment by nicxvan** [comment]
I'm going to install the latest update and see if it's fixed.
