### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nicxvan** [north/generator-style-prototype#14]
I would be interested in putting together some documentation as I go through learning how this works. Would you be available to answer some questions as I go through? 

This would be a complete beginners guide perspective, I have no experience in Sass or compass and I think some of my questions come from there. 

First issue is using the colors and tints that are automatically generated. I am trying to use nth($secondary, 2) my code looks like:
@import "global/colors";
a {
  color: nth($secondary, 2);
}

I get the error:
List index is 2 but list is only 1 item long for 'nth'
I've tried many combinations such as $secondary(2);

color: nth($secondary, 1); does output a css rule,but it's not written. Putting specific css or even a variable color in the project.scss works.

I suspect this is due to inexperience in sass. But I don' tmind writing up documentation if I figure this out and I am reading a compass sass book.

**Comment by nicxvan** [comment]
Sections to consider for documentation:
1 Getting installed (pretty well documented already)
2 Getting started ( also pretty well covered, but I would like to cover from a more tutorial perspective)
3 Exporting to a drupal theme

**Comment by Snugug** [comment]
@nicxvan There isn't really "exporting to a Drupal theme" per se, there is [creation of a Compass extension](https://github.com/Team-Sass/generator-style-prototype#your-compass-extension). That documents how to create and use a Compass extension from the SP you create, which can then be pulled into any project, including a Drupal theme

**Comment by nicxvan** [comment]
Thanks, I'll look into the link you sent. I should have been clearer, I didn't mean an export as in a fully functional theme but more of a how to take the information from the Style Prototype and getting it into something like zen, omega or your own aurora with the least pain.

**Comment by Snugug** [comment]
That's what that link describes, how to create and use a generated Compass extension from your Style Prototype.

**Comment by Snugug** [comment]
Partially a duplication of #25, partially resolved in 2.0 by https://github.com/north/generator-style-prototype#using-your-style-prototype
