### ISSUE TITLE
error running grunt deploy

### ISSUE THREAD

**Issue by codingdesigner** [north/generator-style-prototype#2]
grunt deploy --force
Running "exec:deploy" (exec) task

> > '.dist' does not exist; use 'git subtree add'
> > Exited with code: 1.
> > Warning: Task "exec:deploy" failed. Used --force, continuing.

Done, but with warnings.

**Comment by Snugug** [comment]
Haha, it looks like I totally forgot to do the writeup for `grunt deploy`. The answer is you need to have built your site and committed the .dist file _before_ running it.

**Comment by Snugug** [comment]
This has been documented now
https://github.com/Team-Sass/generator-style-prototype#exporting-final-site
