### ISSUE TITLE
add an element generator, similar to component generator

### ISSUE THREAD

**Issue by codingdesigner** [north/generator-style-prototype#26]
I think we need an element generator that works nearly the same as the component generator, except that it creates the sass for _item _extend and _mixin in the elements directory, and doesn't create html templates or components.

**Comment by Snugug** [comment]
Also refactor elements so that they can be self-documenting the same way components are (or do by hand)

**Comment by Snugug** [comment]
As there is no longer a need to wrap the extends, do you think this is still a priority?
