### ISSUE TITLE
grunt build fails

### ISSUE THREAD

**Issue by solutiondrop** [north/generator-style-prototype#3]
I'm getting the following error when I run 'grunt build' or 'grunt export'. 

```
    >> Running "generator:dist" (generator) task
>> >> unchanged: colors/index.html
>> Warning: The partial messages could not be found Use --force to continue.
>>
>> Aborted due to warnings.
Warning: Task "parallel:assets" failed. Use --force to continue.
```

Aborted due to warnings.

Unfortunately, I can't figure out the problem.
Thanks.

**Comment by chrisfromredfin** [comment]
I have this same issue. I did not run the yeoman generator with --git (nor, of course, --commit). Does that matter?

**Comment by Snugug** [comment]
There is a fix for this on the way for future versions, but you can fix it right now in your work.

Open up `Gruntfile.js`, find `generator:dev:options:partialsGlob` (probably around line 125), and copy that line. Paste that line in place of `generator:dist:options:partialsGlob` (probably around like 142). Those two should look identical. This will solve the build issues.
