### ISSUE TITLE
grunt-open

### ISSUE THREAD

**Issue by robwierzbowski** [north/generator-style-prototype#30]
I noticed you're using an exec task to launch the browser ([here](https://github.com/Team-Sass/generator-style-prototype/blob/master/app/templates/_gruntfile.js#L491-L497)). There's a grunt task that does the same called [grunt-open](https://github.com/jsoverson/grunt-open) (actually what grunt-contrib-connect uses to launch the browser). Thought you might be interested / might give you less to maintain.

**Comment by Snugug** [comment]
Looks good to me. PR welcome, or I'll get around to it eventually

**Comment by Snugug** [comment]
Moved to Browser Sync for 2.0
