### ISSUE TITLE
gh-pages not rendering correctly on the front-end

### ISSUE THREAD

**Issue by danielroot** [north/generator-style-prototype#33]
After running "grunt deploy" I go to the gh-pages URL for my repo http://danrootdesign.github.io/nm-styleguide/ and I get a 404. I can get to elements page here: http://danrootdesign.github.io/nm-styleguide/elements/, but the Assets and pages aren't linking up correctly. This is the link to the CSS <link rel="stylesheet" href="/page/css/prototype.css">. Is there a step I'm missing to make this work? thanks!

**Comment by Snugug** [comment]
The index issue I'm aware of and needs to be fixed (there currently isn't a root index file when exporting). As for your assets not loading, in `config.yml`, there is an asset prefix option. You need to set this to the name of your GitHub directory, specifically for you `nm-styleguide`

**Comment by danielroot** [comment]
Thanks, that did the trick! Great work on this project.
