### ISSUE TITLE
Difficulties understanding _extends.scss / _mixins.scss / template approach ...

### ISSUE THREAD

**Issue by ducdebreme** [north/generator-style-prototype#37]
I attended snugug's lab at the Drupalcon in Prague and I really enjoy the generator. I would like to use it for future projects... 

But I am struggeling with the approach of creating a structures like

```
_html.scss
html/_extends.scss
html/_mixins.scss
```

I was about to set the font sizes and line heights, but I don't understand where to define them? 
Why do we have the variable $html-extendables-extended ? Why should I set it?

```
$html-extendables-extended: false !default;

@if not ($html-extendables-extended) {
  %html-base {
    @include html-base($extend: false, $font-size: $base-size, $line-height: $base-line-height);
  }
}

$html-extendables-extended: true;
```

Is there a post somewhere, that describes the theory behind?

**Comment by Snugug** [comment]
I am in the process of creating a writeup explaining the different pieces and why they are written like they are

**Comment by ducdebreme** [comment]
I am very much looking forward to it!
Am 10.11.2013 16:44 schrieb "Snugug" notifications@github.com:

**Comment by Snugug** [comment]
Full writeup to this approach can be found in [North](http://pointnorth.io/#styling)
