### ISSUE TITLE
grunt server fails when saving sass files

### ISSUE THREAD

**Issue by TylerFisher** [north/generator-style-prototype#38]
Watch command out of parallel task never works.

`Warning: Task "parallel:watch" failed. Use --force to continue.`

However, compass continues to run despite the server stopping.

```
Running "watch" task
Waiting...>>> Compass is polling for changes. Press Ctrl-C to Stop.
>>> Change detected at 21:35:07 to: global/variables/_colors.scss
    >>
    Warning: Task "parallel:watch" failed. Use --force to continue.

Aborted due to warnings.
bash-3.2$ >>> Change detected at 21:35:08 to: global/variables/_colors.scss
```

UPDATE: removing the `watch` task from parallel:watch seems to make everything run smoothly. Obviously, now I can't update config and such without restarting the server.

**Comment by Snugug** [comment]
I'm not entirely sure what you're attempting to do. Are you trying to run `grunt watch` without running `grunt server`?

**Comment by TylerFisher** [comment]
Sorry, this got unclear. Running `grunt server`, `watch` within `parallel:watch` fails after saving over any files. This quits the server, so I cannot view files locally, but `compass:dev` continues to run.  Removing `watch` from the `parallel:watch` command from `Gruntfile.js` makes the server continue to run, and Compass works fine. I just can't update anything other than CSS without restarting the server.

**Comment by Snugug** [comment]
Can you run it with `--force` so we can see where it's failing?

**Comment by TylerFisher** [comment]
Ran, saved over `pages/style-tile/index.html`

```
grunt server --force
Running "server" task

Running "bundler" task

Running "exec:bundle:." (exec) task
Using chunky_png (1.2.9)
Using fssm (0.2.10)
Using sass (3.2.12)
Using compass (0.12.2)
Using breakpoint (2.0.7)
Using compass-blend-modes (0.0.2)
Using color-schemer (0.2.7)
Using compass-normalize (1.4.3)
Using sassy-math (1.5)
Using modular-scale (1.0.6)
Using sassy-strings (1.0.0)
Using singularitygs (1.1.2)
Using toolkit (1.3.8)
Using style-prototypes (1.3.0)
Using bundler (1.3.5)
Your bundle is complete!
It was installed into ./.vendor

Running "create-components" task

Running "copy:dev" (copy) task
Created 35 directories, copied 310 files

Running "uglify:dev" (uglify) task
File ".www/js/main.js" created.

Running "generator:dev" (generator) task
>> changed: style-tile/index.html

Running "jshint:all" (jshint) task
>> 1 file lint free.

Running "csslint:all" (csslint) task
>> 1 files lint free.

Running "connect:server" (connect) task
Started connect web server on localhost:8000.

Running "parallel:watch" (parallel) task
Running "compass:dev" (compass) task
Running "watch" task
Waiting...>>> Compass is polling for changes. Press Ctrl-C to Stop.
    >>
    Warning: Task "parallel:watch" failed. Used --force, continuing.

Done, but with warnings.
```

**Comment by TylerFisher** [comment]
This was an issue with OS X 10.9 and an outdated version of Node. see: https://github.com/gruntjs/grunt-contrib-watch/issues/204
