### ISSUE TITLE
Support Less, in addition to Sass

### ISSUE THREAD

**Issue by webmaven** [north/generator-style-prototype#45]
Can this project support the Less syntax in addition to Sass?

**Comment by Snugug** [comment]
Less is simply unable to handle the complexity needed to support the Style Prototype workflow and has no where near the community support of Sass (outside of Bootstrap, which [is not and will not be supported](https://github.com/Team-Sass/generator-style-prototype/issues/48#issuecomment-35831366)). As such, Less will not be supported by Style Prototypes.
