### ISSUE TITLE
'grunt server' fails on Windows

### ISSUE THREAD

**Issue by webmaven** [north/generator-style-prototype#46]
To successfully watch on Windows, Compass needs the wdm gem, which requires the DevKit for installation.

I am now able to install DevKit and wdm to the system, but can't figure out how to now get it into the bundle that Style Prototype is using.

**Comment by Snugug** [comment]
Add the gem to **compass->dependencies** in **config.yml**. Please also file an [issue with Compass](https://github.com/chriseppstein/compass/issues?direction=desc&sort=updated&state=open) if that dependency isn't automatically fulfilled with Bundler.

**Comment by webmaven** [comment]
Thanks, that worked!

There are issues already, but they've been closed:
https://github.com/chriseppstein/compass/issues/1410
https://github.com/chriseppstein/compass/issues/1470

I don't understand what's happening here well enough to be confident of re-opening the issues.

EDIT: Looks like it is getting mentioned in other issues that are open, like https://github.com/chriseppstein/compass/issues/1548#issuecomment-34429572

**Comment by Snugug** [comment]
I'll take a look at those issues.
