### ISSUE TITLE
Sass installation failure

### ISSUE THREAD

**Issue by ebowers** [north/generator-style-prototype#47]
Sorry if this is a silly question, I'm still learning to use the terminal. But when I run the yeoman generator installer, I am getting this failure with sass. Not sure what is going on, if you have a free moment I would really appreciate any help at all.

Installing sass (3.3.0.rc.4) 
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

....and then down at the bottom ....

An error occurred while installing sass (3.3.0.rc.4), and Bundler cannot
continue.
Make sure that `gem install sass -v '3.3.0.rc.4'` succeeds before bundling.

> > Exited with code: 5.
> > Warning: Task "exec:bundle:." failed. Use --force to continue.

**Comment by Snugug** [comment]
Hmm, this sounds like a Sass issue. A quick search of the [Sass issue queue](https://github.com/nex3/sass/issues?direction=desc&sort=updated&state=open) doesn't yield any issues, so open one up there. I'm going to keep this issue open to track your progress. When you open the issue on the Sass issue queue, please include team-sass/generator-style-prototype#47 in the description

**Comment by crucialfelix** [comment]
Its missing rake. You can see it if you run bundle install manually

```
    bundle install
    Fetching gem metadata from https://rubygems.org/..............
    Fetching gem metadata from https://rubygems.org/..
    Resolving dependencies...
    Using chunky_png (1.3.0)
    Using multi_json (1.8.4)
    Installing sass (3.3.0.rc.5)
    Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby mkrf_conf.rb
    Ensuring you have the right version of listen installed.
    Installing listen >= 1.1.0, < 2.5

    rake RUBYARCHDIR=/Users/crucial/Downloads/mattermind/.vendor/ruby/2.0.0/gems/sass-3.3.0.rc.5/lib RUBYLIBDIR=/Users/crucial/Downloads/mattermind/.vendor/ruby/2.0.0/gems/sass-3.3.0.rc.5/lib
    /Library/Ruby/Site/2.0.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'rake' (>= 0) among 8 total gem(s) (Gem::LoadError)
        from /Library/Ruby/Site/2.0.0/rubygems/dependency.rb:309:in `to_spec'
        from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
        from /usr/bin/rake:22:in `<main>'


    Gem files will remain installed in /Users/crucial/Downloads/mattermind/.vendor/ruby/2.0.0/gems/sass-3.3.0.rc.5 for inspection.
    Results logged to /Users/crucial/Downloads/mattermind/.vendor/ruby/2.0.0/gems/sass-3.3.0.rc.5/ext/gem_make.out
```

Fix for me was to add "rake" to the Gemfile.  I'm not that familiar with gems but I often get this kind of dependency error. Not sure if this is the best fix.  It probably is a Sass issue.

**Comment by Snugug** [comment]
For further help installing Sass properly, please read our [new installation instructions](https://github.com/north/generator-style-prototype#installation)
