### ISSUE TITLE
Creating a style guide based on Bootstrap

### ISSUE THREAD

**Issue by webmaven** [north/generator-style-prototype#48]
Is there a way to use Bootstrap as the basis for a Style Prototype? How would I go about that?

**Comment by Snugug** [comment]
While I understand people like Bootstrap, the entire purpose of Style Prototypes is to create your own components, create your own layouts, to not use a pre-designed CSS System like Bootstrap or Foundation. As such, there is not and will not be an official way to create a Bootstrap based Style Prototype.

That being said, there is nothing stopping you from pulling in Bootstrap through a Compass extension or Bower and writing out all of their components and layouts by hand. I wouldn't recommend it, but you could.

**Comment by webmaven** [comment]
You misunderstand me. I don't want to replicate all of Bootstrap's documentation, I am creating what amounts to a theme that extends Bootstrap a bit, and only want to document the parts of Bootstrap that I am using as well as the parts that I am extending (for example via mixins).

**Comment by Snugug** [comment]
I believe my answer stands. Style Prototypes are not meant to be used with a CSS System, they are meant to create your own. With that said, there is nothing stopping you from pulling in Bootstrap from  somewhere else and creating the components and layouts you want by hand. In fact, all of pieces that make up a Style Prototype are available for you to edit to your heart's content in the system.
