### ISSUE TITLE
yo style-prototype fails (unpredictably) if client name includes apostrophe

### ISSUE THREAD

**Issue by chrisfromredfin** [north/generator-style-prototype#5]
I had a client with the word "Mommy's" in their client name. I tried generating a style-prototype three times, each failing in different ways. However, the third way led me to believe an apostrophe was causing the error. (Looked like compilation errors, like "expected } got '")

Not sure if this is something to fix in code or in documentation.

**Comment by chrisfromredfin** [comment]
p.s. I crtl-C'd the yo process just to see, then ran grunt-server. that one consistently failed on uglification.

**Comment by Snugug** [comment]
Failing unpredictably is hard to debug. If it's failing at uglification, it sounds like a JavaScript issue. Without a paired down, reproducable way to create this error, it's going to be hard for me to fix/

**Comment by chrisfromredfin** [comment]
Well, it's FAILING unpredictably, but it is reproduceable, by using the name "Mommy's Event BFF" in the wizard of  'yo style-prototype'

I changed the name to 'ceylan' (the client's actual name) and then it worked flawlessly.

If it helps, I went back in my cli history and found this:

Running "jshint:all" (jshint) task
Linting js/main.js...ERROR
[L1:C20] Expected ')' and instead saw 's'.
console.log('Mommy's Event BFF');
[L1:C21] Missing semicolon.
console.log('Mommy's Event BFF');
[L1:C22] Expected 'Event' to have an indentation at 1 instead at 22.
console.log('Mommy's Event BFF');
[L1:C22] Expected an assignment or function call and instead saw an expression.
console.log('Mommy's Event BFF');
[L1:C27] Missing semicolon.
console.log('Mommy's Event BFF');
[L1:C31] Unclosed string.
console.log('Mommy's Event BFF');

> > Cannot read property 'id' of undefined

...which is what first tipped me off that it's probably the apostrophe.

Let me know how else I can help. (I went to both your presentations at Design 4 Drupal and this is my first foray into ANY of this. But it's _rocking. my world!_)

So this may not be a style prototypes issue but a JS lint issue; or, maybe you need to be escaping the client name or making a 'variable-safe' version, or like I said, just adding some documentation/help text to not use apostrophes in the client name.

**Comment by Snugug** [comment]
Take a look at your `main.js` file. I'm using single quotes in the [`console.log`](https://github.com/Team-Sass/generator-style-prototype/blob/master/app/templates/main.js) there, and that's then providing broken JS when compiling your JS. I will update future versions of the generator to solve this problem. Remove that line from your `main.js` file, or change the single quotes to double quotes, and you'll be good to go.

As for how to debug this yourself, JSLint actually provides all of the answers for you:

```
Running "jshint:all" (jshint) task
Linting js/main.js...ERROR
[L1:C20] Expected ')' and instead saw 's'.
console.log('Mommy's Event BFF');
[L1:C21] Missing semicolon.
console.log('Mommy's Event BFF');
[L1:C22] Expected 'Event' to have an indentation at 1 instead at 22.
console.log('Mommy's Event BFF');
[L1:C22] Expected an assignment or function call and instead saw an expression.
console.log('Mommy's Event BFF');
[L1:C27] Missing semicolon.
console.log('Mommy's Event BFF');
[L1:C31] Unclosed string.
console.log('Mommy's Event BFF');
```

JSLint had an error, line 1, column 20. It was expecting a `)` at the end of the close string, it didn't get it, it saw an `s` instead. Column 21, expecting the `)`, it then next expected a semicolon, which was then missing. The errors kind of cascade from there. It will fail at the same place in Build.
