### ISSUE TITLE
upgrade csslint

### ISSUE THREAD

**Issue by thiagodemellobueno** [north/generator-style-prototype#55]
updgrading grunt-contrib-csslint to "~0.2.0" and thus csslint to 0.10.0
prevents several possible build errors, improving compatability with ie10/windows phone 8 and other libraries (bootstrap… i know).

**Comment by Snugug** [comment]
CSS Lint has been removed from Style Prototypes 2.0 as I found it hard to lint Sass files properly. If you would like to have it added back in, please file an issue to do so.
