### ISSUE TITLE
bower components dir not being created. cant run grunt server.

### ISSUE THREAD

**Issue by dilrajahdan** [north/generator-style-prototype#6]
When running 'grunt server' I get the following message in the console: 
# 

Running "server" task

Running "copy:dev" (copy) task
Created 2 directories, copied 9 files

Running "uglify:dev" (uglify) task
File ".www/js/main.js" created.

Running "compass:dev" (compass) task
Errno::ENOENT on line ["33"] of /Users/Dappa/.rvm/gems/ruby-1.9.3-p362/gems/compass-0.12.2/lib/compass/exec/global_options_parser.rb: No such file or directory - /Users/Dappa/Sites/yummy-cakes/components
Run with --trace to see the full backtrace
Warning: Task "compass:dev" failed. Use --force to continue.

Aborted due to warnings.
# 

I have tried running 'bower install -f' manually and get the following: 
# 

bower formalize#\*              resolve git://github.com/nathansmith/formalize.git#*
bower prism#\*                  resolve git://github.com/LeaVerou/prism.git#*
bower Element.details#\*        resolve git://github.com/termi/Element.details.git#*
bower formalize#\*             checkout master
bower Element.details#\*       checkout master
bower modernizr#~2.6.2         resolve git://github.com/Modernizr/Modernizr.git#~2.6.2
bower jquery#~2.0.0            resolve git://github.com/components/jquery.git#~2.0.0
bower jquery#~2.0.0           download http://github.com/components/jquery/archive/2.0.3.tar.gz
bower modernizr#~2.6.2        download http://github.com/Modernizr/Modernizr/archive/v2.6.2.tar.gz
bower jquery#~2.0.0            extract archive.tar.gz
bower modernizr#~2.6.2         extract archive.tar.gz
bower prism#\*             ENORESTARGET Tag/branch master does not exist

Additional error details:
No tags found in git://github.com/LeaVerou/prism.git
Available branches: gh-pages
# 

Creating a components directory manually allows me to run 'grunt server' but the components are still missing. 

Any ideas?

**Comment by dilrajahdan** [comment]
After a little sleep I got it working by:
- deleting `"prism": "latest",` from `bower.json`
- running `bower install` again which downloaded all component except prism successfully 
- installing prism manually but this time specifying the target as 'bower install prism#gh-pages' 

Does the line `"prism": "latest",` in `bower.json` need to change??

Anyway thanks for the awesome work folks! Having a play now!!!

**Comment by Snugug** [comment]
I will look into why the prism download is failing

**Comment by dilrajahdan** [comment]
`"prism": "gh-pages"` in `bower.json` seemed to do the trick

**Comment by Snugug** [comment]
Related to #7

**Comment by nicxvan** [comment]
I was getting this error as well, dilrajahdan's solution worked. Now it fails with Task parallel:remote and Task exec:weinre failed.

**Comment by RonB** [comment]
I have the same issue, only after moving my '/.../www' folder to '/.../client' the compass task won' t run. It gives me:

Warning: Errno::ENOENT on line ["33"] of /var/lib/gems/1.9.1/gems/compass-0.12.7/lib/compass/exec/global_options_parser.rb: No such file or directory - /home/ronald/development/brein/zaken/www

when i move the folder back it all runs fine, but i do need to rename the www folder.

There's no prism in my bower.json. I've tried bower install -f but no luck.

Somehow the ruby global options parsers retrieves the previous path and does not use the compass settings in my gruntfile.js:

```
                compass: {
                        options: {
                                sassDir: "<%= yeoman.app %>/styles",
                                cssDir: ".tmp/styles",
                                generatedImagesDir: ".tmp/styles/ui/images/",
                                imagesDir: "<%= yeoman.app %>/styles/ui/images/",
                                javascriptsDir: "<%= yeoman.app %>/scripts",
                                fontsDir: "<%= yeoman.app %>/fonts",
                                importPath: "<%= yeoman.app %>/bower_components",
                                httpImagesPath: "styles/ui/images/",
                                httpGeneratedImagesPath: "styles/ui/images/",
                                httpFontsPath: "fonts",
                                relativeAssets: true
                        }
```

.....

The yeamoan app variable is changed to client. The variable which is ginving the trouble is probably  the importPath because that is what it syas in the ruby script global_options_parser.rb on line 33:

.....
        ::Compass.configuration.add_import_path Pathname.new(import_path).realpath
.....

Any ideas would be welcome....
