### ISSUE TITLE
Next Steps?

### ISSUE THREAD

**Issue by fallenturtle** [north/generator-style-prototype#60]
Once we have styles and pages composed of components, how do we start using these to build the actual site outside of the styleguide? Is there an export option or a way to build the actual site using these patterns (aka &lt;pattern data-name="foo" data-source="components"&gt;)?

**Comment by Snugug** [comment]
The pattern tag is just some syntactical sugar around Angular's `ng-include` that uses a lookup to find the include path. Take a look at the 2.0.0 release and the updated README
