### ISSUE TITLE
Mark as unmaintained

### ISSUE THREAD

**Issue by lewisnyman** [north/generator-style-prototype#70]
It is dangerous to start a project on this tool. It should be clear that it is unmaintained.

**Comment by cmcintosh** [comment]
who takes these types of projects seriously anyway?  its more of a gimmick than anything

**Comment by lewisnyman** [comment]
That's not a fair comment, a lot of work was put into this project.

**Comment by cmcintosh** [comment]
What I am saying, is things generally are not to the point where you can do cloud based development. Sorry for not being specific. [Correction on previous statement]

**Comment by Snugug** [comment]
You're right, will do.

**Comment by Snugug** [comment]
Closed by https://github.com/north/generator-style-prototype/commit/bdaea0349fdaf15a4683e39cdb41f40c3f2bae6d
